apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: rg.fr-par.scw.cloud/ns-toolong/too-long-backend:0.1
        ports:
          - containerPort: 8080
        env:
          - name: DB_HOST
            value: postgres-service
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: toolonguser
          - name: DB_PASSWORD
            value: too-long-pass
          - name: DB_NAME
            value: postgres

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: backend.51.159.8.169.nip.io
      http:
        paths:
          - path: /links
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80


