apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kamloic/tl-frontend:0.1
        ports:
          - containerPort: 3000
        env:
          - name: REACT_APP_BACKEND_URL
            value: http://backend.172.16.110.7.nip.io/links
      imagePullSecrets:
         - name: ghcr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: frontend.172.16.110.7.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80







