name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and push Docker image
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: kamloiic/tl-backend
        run: |
          curl -sSL https://github.com/buildpacks/pack/releases/latest/download/pack-${RUNNER_OS}-${RUNNER_ARCH}.tar.gz | sudo tar xz -C /usr/local/bin
          
          # Build and push image
          pack build $REGISTRY/$IMAGE_NAME \
            --builder paketobuildpacks/builder:base \
            --path ./backend \
            --publish

      - name: Configure Docker CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy to GitHub Container Registry
        run: |
          IMAGE_NAME=${{ env.IMAGE_NAME }}
          REGISTRY=${{ env.REGISTRY }}
          
          # Add image tags
          docker tag $IMAGE_NAME:latest $REGISTRY/$IMAGE_NAME:latest

          # Push images
          docker push $REGISTRY/$IMAGE_NAME:latest

      - name: Cleanup Docker images
        run: |
          docker image prune -f

